### ISSUE TITLE
What'd people think of the documentary?

### ISSUE THREAD

**Issue by elimisteve** [lucyparsons/meetingslides#1]
I am always in search of compelling material to show people at the surveillance self-defense workshops I do, and I hadn't heard of this documentary.

Did people like it? interesting parallels to today's surveillance regime?  Were there particular parts of the documentary that were especially compelling that I could perhaps show in a self-contained manner?

Thanks!

**Comment by b-meson** [comment]
Hi @elimisteve Sorry I didn't reply earlier, we don't have an automatic way of getting notifications on new issues. 

The documentary was very good for having about 10-15 people to view it. We were able to have a pretty long discussion afterwards about the ways systems of control work and how they relate to modern systems of surveillance. Also, it contained a lot of great quotes... for example "Trust is good, control is better". So its definitely worth watch in a group of like minded people. Protip: if you order it, try the amazon.de domain since i couldn't find it in the US. 

Feel free to email me with questions @elimisteve I believe you have my email.
